# Generated by Django 2.1.8 on 2019-08-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_press'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Press')),
            ],
        ),
    ]
