# Generated by Django 2.1.8 on 2019-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('books', models.ManyToManyField(to='app01.Book')),
            ],
        ),
    ]
